# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='sender_mailaddress',
            new_name='Receiver',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='to_mailaddress',
            new_name='Sender',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='subject',
            new_name='Subject',
        ),
    ]
