# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_mail_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='author',
            new_name='user',
        ),
    ]
