# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_remove_mail_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='is_deleted_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='is_deleted_sender',
            field=models.BooleanField(default=False),
        ),
    ]
