# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_auto_20170808_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='is_deleted_sender',
            field=models.BooleanField(default=True),
        ),
    ]
